### ISSUE TITLE
Default MASTER branch should be converted to MAIN branch

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/dellemc.os9#20]
##### SUMMARY
According to the [collection requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#branch-name-and-configuration),
default branches of the existing repositories under `ansible_collections` SHOULD be converted to use main.

**Comment by komalupatil** [comment]
we are ok to rename master branch to main

**Comment by skg-net** [comment]
Done

**Comment by Andersson007** [comment]
Thank you!
